name: "CI/CD Stage 3 Deploy to Prod"

on:
  workflow_call:

permissions: {}

jobs:
  # Add prod app deploy

  deploy-prod-spec:
    name: "Deploy Specification to Production"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Python Dependencies
        uses: ./.github/actions/setup-python-dependencies
      - name: Setup proxygen
        uses: ./.github/actions/setup-proxygen
        with:
          PTL_PROXYGEN_CLIENT_ID: ${{ secrets.PTL_PROXYGEN_CLIENT_ID }}
          PTL_PROXYGEN_KEY_ID: ${{ secrets.PTL_PROXYGEN_KEY_ID }}
          PTL_PROXYGEN_PRIVATE_KEY: ${{ secrets.PTL_PROXYGEN_PRIVATE_KEY }}
      - name: Deploy Specification to Production
        run: make deploy-spec-prod-ci
        env:
          # Variables are necessary for spec generation, but aren't used in compiled spec
          ENVIRONMENT: "prod"
          PROXYGEN_URL_PATH: "im1-pfs-auth"
          CONTAINER_TAG: "latest"
